### ISSUE TITLE
Data mapping issue?

### ISSUE THREAD

**Issue by micahwalter** [mplusmuseum/mplusmuseum-graphql#11]
I'm not sure why this would be, but it seems like there is data in ES that is not finding its way through to GraphQL. 

This object, ID 2999 has a title in ES

```
    "titles": [
      [
        {
          "text": "Pink Sofa",
          "lang": "en"
        },
        {
          "text": "粉色沙發",
          "lang": "zh-hant"
        }
      ]
    ],
```

But when I query it in GraphQL I get the following

```
{
  "data": {
    "artwork": {
      "id": "2999",
      "titles": [
        {
          "lang": null,
          "text": null
        }
      ]
    }
  }
}
```

**Comment by jedahan** [comment]
Looking into this, but my gut instinct is that the data is elasticsearch is not well formatted, and should be a single array, not an array of arrays.

Because we are using a schema for graphql, we probably want to conform to that schema on the import side. If the parsing fails due to inconsistent schema (for example, [ [ DATA ] ] instead of  [ DATA ]), we should raise an exception, allows us to give a list of TMS data that needs to be cleaned up.

The alternative is to write adapters/resolvers for graphql that can handle both, but this will get messy very quickly, hiding inconsistencies from us leading to subtle bugs later, especially when we start allowing writing to the db.

**Comment by micahwalter** [comment]
this seems fixed now, right?

**Comment by revdancatt** [comment]
Yup this is fixed :)
